server.port=8081
calculator.url=http://localhost:8080

spring.application.name=ms_deal
logging.file.name=MS_Deal/logs/app.log
logging.file.path=logs

spring.datasource.url=jdbc:postgresql://localhost:5432/neoflex_calculator
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.main.allow-bean-definition-overriding=true
spring.liquibase.change-log=db/changelog/changelog.xml
spring.liquibase.url=${spring.datasource.url}
spring.liquibase.user=${spring.datasource.username}
spring.liquibase.password=${spring.datasource.password}

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.retry.topic.delay=5s