server.port=8084
spring.application.name=MS_Gateway

deal.url=http://localhost:8081
statement.url=http://localhost:8082

logging.file.name=MS_Gateway/logs/app.log
logging.file.path=logs

spring.liquibase.enabled=false