server.port=8083

logging.file.name=logs/app.log
logging.file.path=logs

spring.main.allow-bean-definition-overriding=true
spring.application.name=MS_Dossier
spring.liquibase.enabled=false

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.listener.ack-mode=record

spring.kafka.producer.client-id=ms_deal
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=ru.dossier.kafka.config.DltMessageSerializer
spring.kafka.producer.retries=3

spring.kafka.consumer.group-id=${spring.application.name}
spring.kafka.consumer.autoOffsetReset=earliest
spring.kafka.consumer.keyDeserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.valueDeserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.properties.spring.json.value.default.type=ru.deal.dto.EmailMessageDto
spring.kafka.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer